services:
  test-app-k6-laravel-tweaked-frankenphp:
    build:
      context: .
      dockerfile: ./dockerfile/tweaked-frankenphp.Dockerfile
    container_name: test-app-k6-laravel-tweaked-frankenphp
    image: test-app-k6-laravel-tweaked-frankenphp:1.0.0
    environment:
      - SESSION_DRIVER=file
      - DB_CONNECTION=mysql
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_DATABASE=test-app-k6
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - CACHE_DRIVER=redis
      - REDIS_PREFIX=
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
    mem_limit: 256m
    cpus: 1

  test-app-k6-laravel-tweaked-frankenphp-nginx:
    image: nginx:latest
    container_name: test-app-k6-laravel-tweaked-frankenphp-nginx
    ports:
      - "8002:80"
    volumes:
      - ./nginx/default-tweaked-frankenphp.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - test-app-k6-laravel-tweaked-frankenphp
    mem_limit: 256m
    cpus: 1